INSERT INTO restaurants (name) VALUES
                                   ('Navat'), ('Faiza'), ('Chicken Star'), ('Baan Baan'), ('Pur Pur'),
                                   ('Pappa Johns'), ('Dodo Pizza'), ('Bulochnaya'), ('Frunze'), ('Social Coffee');

INSERT INTO dishes (name, price, restaurant_id) VALUES
                                                    ('Плов праздничный', 350, (SELECT id FROM restaurants WHERE name = 'Navat')),
                                                    ('Манты с говядиной', 280, (SELECT id FROM restaurants WHERE name = 'Navat')),
                                                    ('Жареный лагман', 310, (SELECT id FROM restaurants WHERE name = 'Navat')),
                                                    ('Шорпо классическое', 260, (SELECT id FROM restaurants WHERE name = 'Navat')),
                                                    ('Бешбармак', 450, (SELECT id FROM restaurants WHERE name = 'Navat')),
                                                    ('Куурдак из баранины', 420, (SELECT id FROM restaurants WHERE name = 'Navat')),
                                                    ('Самса тандырная', 95, (SELECT id FROM restaurants WHERE name = 'Navat')),
                                                    ('Боорсоки (порция)', 120, (SELECT id FROM restaurants WHERE name = 'Navat')),
                                                    ('Салат Ачик-Чучук', 150, (SELECT id FROM restaurants WHERE name = 'Navat')),
                                                    ('Чай с облепихой', 200, (SELECT id FROM restaurants WHERE name = 'Navat')),
                                                    ('Чучук (нарезка)', 380, (SELECT id FROM restaurants WHERE name = 'Navat')),
                                                    ('Гульчетай', 330, (SELECT id FROM restaurants WHERE name = 'Navat')),
                                                    ('Аткан-чай', 150, (SELECT id FROM restaurants WHERE name = 'Navat')),
                                                    ('Дымдама', 390, (SELECT id FROM restaurants WHERE name = 'Navat')),
                                                    ('Каттама', 110, (SELECT id FROM restaurants WHERE name = 'Navat'));

INSERT INTO dishes (name, price, restaurant_id) VALUES
                                                    ('Лагман по-уйгурски', 290, (SELECT id FROM restaurants WHERE name = 'Faiza')),
                                                    ('Мампар', 250, (SELECT id FROM restaurants WHERE name = 'Faiza')),
                                                    ('Ганфан', 280, (SELECT id FROM restaurants WHERE name = 'Faiza')),
                                                    ('Пельмени в бульоне', 230, (SELECT id FROM restaurants WHERE name = 'Faiza')),
                                                    ('Котлета с пюре', 320, (SELECT id FROM restaurants WHERE name = 'Faiza')),
                                                    ('Салат Ташкент', 180, (SELECT id FROM restaurants WHERE name = 'Faiza')),
                                                    ('Бризоль', 340, (SELECT id FROM restaurants WHERE name = 'Faiza')),
                                                    ('Окрошка', 160, (SELECT id FROM restaurants WHERE name = 'Faiza')),
                                                    ('Пирожное Картошка', 80, (SELECT id FROM restaurants WHERE name = 'Faiza')),
                                                    ('Компот ягодный', 60, (SELECT id FROM restaurants WHERE name = 'Faiza')),
                                                    ('Ашлян-фу', 150, (SELECT id FROM restaurants WHERE name = 'Faiza')),
                                                    ('Чебурек с мясом', 110, (SELECT id FROM restaurants WHERE name = 'Faiza')),
                                                    ('Суп Фрикадельки', 240, (SELECT id FROM restaurants WHERE name = 'Faiza')),
                                                    ('Манты с джусаем', 260, (SELECT id FROM restaurants WHERE name = 'Faiza')),
                                                    ('Чай с лимоном', 40, (SELECT id FROM restaurants WHERE name = 'Faiza'));

INSERT INTO dishes (name, price, restaurant_id) VALUES
                                                    ('Каннам стайл крылышки', 480, (SELECT id FROM restaurants WHERE name = 'Chicken Star')),
                                                    ('Острая грудка', 450, (SELECT id FROM restaurants WHERE name = 'Chicken Star')),
                                                    ('Чикен бургер', 380, (SELECT id FROM restaurants WHERE name = 'Chicken Star')),
                                                    ('Рамен классик', 350, (SELECT id FROM restaurants WHERE name = 'Chicken Star')),
                                                    ('Кимчи тиге', 390, (SELECT id FROM restaurants WHERE name = 'Chicken Star')),
                                                    ('Ттокпокки', 320, (SELECT id FROM restaurants WHERE name = 'Chicken Star')),
                                                    ('Рис с овощами', 180, (SELECT id FROM restaurants WHERE name = 'Chicken Star')),
                                                    ('Салат из проростков', 150, (SELECT id FROM restaurants WHERE name = 'Chicken Star')),
                                                    ('Лимонад имбирный', 220, (SELECT id FROM restaurants WHERE name = 'Chicken Star')),
                                                    ('Корейский чай', 140, (SELECT id FROM restaurants WHERE name = 'Chicken Star')),
                                                    ('Кимбап классик', 290, (SELECT id FROM restaurants WHERE name = 'Chicken Star')),
                                                    ('Курица в медовом соусе', 460, (SELECT id FROM restaurants WHERE name = 'Chicken Star')),
                                                    ('Картофельные дольки', 150, (SELECT id FROM restaurants WHERE name = 'Chicken Star')),
                                                    ('Салат Панчан', 120, (SELECT id FROM restaurants WHERE name = 'Chicken Star')),
                                                    ('Морковный торт', 280, (SELECT id FROM restaurants WHERE name = 'Chicken Star'));

INSERT INTO dishes (name, price, restaurant_id) VALUES
                                                    ('Том Ям с креветками', 550, (SELECT id FROM restaurants WHERE name = 'Baan Baan')),
                                                    ('Пад Тай', 420, (SELECT id FROM restaurants WHERE name = 'Baan Baan')),
                                                    ('Зеленый Карри', 480, (SELECT id FROM restaurants WHERE name = 'Baan Baan')),
                                                    ('Салат Сом Там', 350, (SELECT id FROM restaurants WHERE name = 'Baan Baan')),
                                                    ('Манго Стики Райс', 380, (SELECT id FROM restaurants WHERE name = 'Baan Baan')),
                                                    ('Курица с кешью', 440, (SELECT id FROM restaurants WHERE name = 'Baan Baan')),
                                                    ('Стеклянная лапша', 390, (SELECT id FROM restaurants WHERE name = 'Baan Baan')),
                                                    ('Тайские спринг-роллы', 280, (SELECT id FROM restaurants WHERE name = 'Baan Baan')),
                                                    ('Кокосовое молоко', 150, (SELECT id FROM restaurants WHERE name = 'Baan Baan')),
                                                    ('Тайский синий чай', 190, (SELECT id FROM restaurants WHERE name = 'Baan Baan')),
                                                    ('Том Кха', 520, (SELECT id FROM restaurants WHERE name = 'Baan Baan')),
                                                    ('Лапша со свининой', 380, (SELECT id FROM restaurants WHERE name = 'Baan Baan')),
                                                    ('Тайский омлет', 250, (SELECT id FROM restaurants WHERE name = 'Baan Baan')),
                                                    ('Салат с говядиной', 410, (SELECT id FROM restaurants WHERE name = 'Baan Baan')),
                                                    ('Моти кокосовое', 220, (SELECT id FROM restaurants WHERE name = 'Baan Baan'));

INSERT INTO dishes (name, price, restaurant_id) VALUES
                                                    ('Хачапури по-аджарски', 390, (SELECT id FROM restaurants WHERE name = 'Pur Pur')),
                                                    ('Хинкали классические', 70, (SELECT id FROM restaurants WHERE name = 'Pur Pur')),
                                                    ('Сациви с курицей', 420, (SELECT id FROM restaurants WHERE name = 'Pur Pur')),
                                                    ('Лобио в горшочке', 310, (SELECT id FROM restaurants WHERE name = 'Pur Pur')),
                                                    ('Оджахури', 450, (SELECT id FROM restaurants WHERE name = 'Pur Pur')),
                                                    ('Пхали ассорти', 350, (SELECT id FROM restaurants WHERE name = 'Pur Pur')),
                                                    ('Шашлык из свинины', 520, (SELECT id FROM restaurants WHERE name = 'Pur Pur')),
                                                    ('Харчо', 280, (SELECT id FROM restaurants WHERE name = 'Pur Pur')),
                                                    ('Вино домашнее (бокал)', 250, (SELECT id FROM restaurants WHERE name = 'Pur Pur')),
                                                    ('Чурчхела', 150, (SELECT id FROM restaurants WHERE name = 'Pur Pur')),
                                                    ('Хачапури по-имеретински', 360, (SELECT id FROM restaurants WHERE name = 'Pur Pur')),
                                                    ('Хинкали с сыром', 75, (SELECT id FROM restaurants WHERE name = 'Pur Pur')),
                                                    ('Люля-кебаб из телятины', 480, (SELECT id FROM restaurants WHERE name = 'Pur Pur')),
                                                    ('Баклажаны с орехами', 320, (SELECT id FROM restaurants WHERE name = 'Pur Pur')),
                                                    ('Лимонад Натахтари', 180, (SELECT id FROM restaurants WHERE name = 'Pur Pur'));

INSERT INTO dishes (name, price, restaurant_id) VALUES
                                                    ('Супер Папа 30см', 650, (SELECT id FROM restaurants WHERE name = 'Pappa Johns')),
                                                    ('Мясная классика', 680, (SELECT id FROM restaurants WHERE name = 'Pappa Johns')),
                                                    ('Маргарита сочная', 450, (SELECT id FROM restaurants WHERE name = 'Pappa Johns')),
                                                    ('Сырные палочки', 280, (SELECT id FROM restaurants WHERE name = 'Pappa Johns')),
                                                    ('Крылышки BBQ', 390, (SELECT id FROM restaurants WHERE name = 'Pappa Johns')),
                                                    ('Пепперони', 620, (SELECT id FROM restaurants WHERE name = 'Pappa Johns')),
                                                    ('Гавайская с ананасом', 590, (SELECT id FROM restaurants WHERE name = 'Pappa Johns')),
                                                    ('Салат Цезарь', 340, (SELECT id FROM restaurants WHERE name = 'Pappa Johns')),
                                                    ('Кока-кола 1л', 120, (SELECT id FROM restaurants WHERE name = 'Pappa Johns')),
                                                    ('Чесночный соус', 50, (SELECT id FROM restaurants WHERE name = 'Pappa Johns')),
                                                    ('Пицца 4 сыра', 610, (SELECT id FROM restaurants WHERE name = 'Pappa Johns')),
                                                    ('Ветчина и грибы', 580, (SELECT id FROM restaurants WHERE name = 'Pappa Johns')),
                                                    ('Картофель фри', 130, (SELECT id FROM restaurants WHERE name = 'Pappa Johns')),
                                                    ('Печенье с шоколадом', 150, (SELECT id FROM restaurants WHERE name = 'Pappa Johns')),
                                                    ('Фанта 1л', 120, (SELECT id FROM restaurants WHERE name = 'Pappa Johns'));

INSERT INTO dishes (name, price, restaurant_id) VALUES
                                                    ('Додо Пицца', 580, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza')),
                                                    ('Додстер', 170, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza')),
                                                    ('Картофель из печи', 140, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza')),
                                                    ('Сырный цыпленок', 610, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza')),
                                                    ('Рулетики с корицей', 190, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza')),
                                                    ('Грибной стартер', 160, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza')),
                                                    ('Чизбургер-пицца', 630, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza')),
                                                    ('Кофе Капучино', 160, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza')),
                                                    ('Молочный коктейль', 210, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza')),
                                                    ('Морс черная смородина', 90, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza')),
                                                    ('Мясная с черри', 640, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza')),
                                                    ('Додстер острый', 180, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza')),
                                                    ('Омлет с ветчиной', 210, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza')),
                                                    ('Чизкейк Нью-Йорк', 190, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza')),
                                                    ('Чай Тесс', 80, (SELECT id FROM restaurants WHERE name = 'Dodo Pizza'));

INSERT INTO dishes (name, price, restaurant_id) VALUES
                                                    ('Круассан классический', 110, (SELECT id FROM restaurants WHERE name = 'Bulochnaya')),
                                                    ('Миндальный круассан', 160, (SELECT id FROM restaurants WHERE name = 'Bulochnaya')),
                                                    ('Улитка с изюмом', 95, (SELECT id FROM restaurants WHERE name = 'Bulochnaya')),
                                                    ('Киш с лососем', 240, (SELECT id FROM restaurants WHERE name = 'Bulochnaya')),
                                                    ('Багет французский', 70, (SELECT id FROM restaurants WHERE name = 'Bulochnaya')),
                                                    ('Эклер ванильный', 130, (SELECT id FROM restaurants WHERE name = 'Bulochnaya')),
                                                    ('Сэндвич с тунцом', 280, (SELECT id FROM restaurants WHERE name = 'Bulochnaya')),
                                                    ('Тарталетка с ягодами', 190, (SELECT id FROM restaurants WHERE name = 'Bulochnaya')),
                                                    ('Латте', 180, (SELECT id FROM restaurants WHERE name = 'Bulochnaya')),
                                                    ('Горячий шоколад', 220, (SELECT id FROM restaurants WHERE name = 'Bulochnaya')),
                                                    ('Даниш с вишней', 140, (SELECT id FROM restaurants WHERE name = 'Bulochnaya')),
                                                    ('Панини с курицей', 260, (SELECT id FROM restaurants WHERE name = 'Bulochnaya')),
                                                    ('Ржаной бездрожжевой', 85, (SELECT id FROM restaurants WHERE name = 'Bulochnaya')),
                                                    ('Макарон (3 шт)', 210, (SELECT id FROM restaurants WHERE name = 'Bulochnaya')),
                                                    ('Американо', 140, (SELECT id FROM restaurants WHERE name = 'Bulochnaya'));

INSERT INTO dishes (name, price, restaurant_id) VALUES
                                                    ('Стейк Рибай', 1200, (SELECT id FROM restaurants WHERE name = 'Frunze')),
                                                    ('Лосось на гриле', 850, (SELECT id FROM restaurants WHERE name = 'Frunze')),
                                                    ('Салат с авокадо', 420, (SELECT id FROM restaurants WHERE name = 'Frunze')),
                                                    ('Суп из белых грибов', 380, (SELECT id FROM restaurants WHERE name = 'Frunze')),
                                                    ('Паста Карбонара', 490, (SELECT id FROM restaurants WHERE name = 'Frunze')),
                                                    ('Ризотто с креветками', 560, (SELECT id FROM restaurants WHERE name = 'Frunze')),
                                                    ('Утиная ножка конфи', 780, (SELECT id FROM restaurants WHERE name = 'Frunze')),
                                                    ('Тирамису', 350, (SELECT id FROM restaurants WHERE name = 'Frunze')),
                                                    ('Вино красное сух.', 1800, (SELECT id FROM restaurants WHERE name = 'Frunze')),
                                                    ('Минеральная вода', 150, (SELECT id FROM restaurants WHERE name = 'Frunze')),
                                                    ('Филе миньон', 1400, (SELECT id FROM restaurants WHERE name = 'Frunze')),
                                                    ('Тартар из говядины', 550, (SELECT id FROM restaurants WHERE name = 'Frunze')),
                                                    ('Стейк из семги', 980, (SELECT id FROM restaurants WHERE name = 'Frunze')),
                                                    ('Десерт Павлова', 390, (SELECT id FROM restaurants WHERE name = 'Frunze')),
                                                    ('Эспрессо', 120, (SELECT id FROM restaurants WHERE name = 'Frunze'));

INSERT INTO dishes (name, price, restaurant_id) VALUES
                                                    ('Английский завтрак', 450, (SELECT id FROM restaurants WHERE name = 'Social Coffee')),
                                                    ('Сырники со сметаной', 290, (SELECT id FROM restaurants WHERE name = 'Social Coffee')),
                                                    ('Яйца Бенедикт', 380, (SELECT id FROM restaurants WHERE name = 'Social Coffee')),
                                                    ('Авокадо тост', 410, (SELECT id FROM restaurants WHERE name = 'Social Coffee')),
                                                    ('Панкейки с медом', 260, (SELECT id FROM restaurants WHERE name = 'Social Coffee')),
                                                    ('Омлет с сыром', 240, (SELECT id FROM restaurants WHERE name = 'Social Coffee')),
                                                    ('Раф Кофе', 210, (SELECT id FROM restaurants WHERE name = 'Social Coffee')),
                                                    ('Матча Латте', 230, (SELECT id FROM restaurants WHERE name = 'Social Coffee')),
                                                    ('Гранола с йогуртом', 220, (SELECT id FROM restaurants WHERE name = 'Social Coffee')),
                                                    ('Свежевыжатый сок', 250, (SELECT id FROM restaurants WHERE name = 'Social Coffee')),
                                                    ('Тост с лососем', 480, (SELECT id FROM restaurants WHERE name = 'Social Coffee')),
                                                    ('Овсянка с фруктами', 210, (SELECT id FROM restaurants WHERE name = 'Social Coffee')),
                                                    ('Смузи боул', 350, (SELECT id FROM restaurants WHERE name = 'Social Coffee')),
                                                    ('Флэт Уайт', 190, (SELECT id FROM restaurants WHERE name = 'Social Coffee')),
                                                    ('Круассан завтрак', 320, (SELECT id FROM restaurants WHERE name = 'Social Coffee'));